### ISSUE TITLE
Q: Will this work for MariaDB as well?

### ISSUE THREAD

**Issue by tankchintan** [Yelp/mysql_streamer#13]
I know the name says, it is a mysql streamer. But since MariaDb was forked from MySQL, I am wondering if it can be made to work with even MAriaDB? Also what version of MySQL is supported, only 5.5?

**Comment by HaMo0n** [comment]
I have a same question too

**Comment by joshSzep** [comment]
MariaDB and versions outside 5.5 have not been tested. Primary concern is if they would have binlog compatibility.

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!
