### ISSUE TITLE
Error while trying to run 'make -f Makefile-opensource test' command

### ISSUE THREAD

**Issue by krishnakanth23** [Yelp/mysql_streamer#18]
Hi 
 while running the make -f Makefile-opensource test' command am getting below exception and its cleaning all the setup. Any leads on this will be helpful.

gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/_mysql.o -L/usr/lib -L/usr/lib64 -lmysqlclient -lpthread -lm -lrt -ldl -lpython2.7 -o build/lib.linux-x86_64-2.7/_mysql.so

**/usr/bin/ld: cannot find -lmysqlclient**

collect2: error: ld returned 1 exit status

error: command 'gcc' failed with exit status 1

----------------------------------------
**Failed building wheel for MySQL-python
SLOW!! no wheel found after building (couldn't be wheeled?): MySQL-python==1.2.3**
Installing collected packages: MySQL-python, PyMySQL, PyStaticConfiguration, PyYAML, SQLAlchemy, boto, contextdecorator, data-pipeline, dateglob, enum34, future, futures, ipaddress, iso8601, kafka-python, kazoo, mccabe, mrjob, mysql-replication, pep8, ply, py, pycrypto, pyflakes, pysubnettree, python-dateutil, pytz, requests, send-nsca, setproctitle, simplejson, six, sqlparse, testing.mysqld, thriftpy, vmprof, wheel, yelp-clog, replication-handler, swagger-zipkin, cryptography, cached-property, pyramid-zipkin, data-pipeline-avro-util, pyopenssl, bravado, cffi, yelp-avro, frozendict, kafka-utils, psutil, filechunkio, testing.common.database, py-zipkin, idna, pyasn1, pyramid, fido, bravado-core, twisted, yelp-bytes, crochet, pycparser, requests-futures, retrying, fabric, PasteDeploy, repoze.lru, translationstring, WebOb, zope.deprecation, venusian, hupper, zope.interface, service-identity, jsonschema, swagger-spec-validator, Automat, constantly, incremental, yelp-encodings, paramiko, attrs, pyasn1-modules, functools32, rfc3987, strict-rfc3339, webcolors, ecdsa
  Running setup.py install for MySQL-python
    building '_mysql' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Dversion_info=(1,2,3,'final',0) -D__version__=1.2.3 -I/usr/include/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o -fPIC -g -fabi-version=2 -fno-omit-frame-pointer -fno-strict-aliasing
    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/_mysql.o -L/usr/lib -L/usr/lib64 -lmysqlclient -lpthread -lm -lrt -ldl -lpython2.7 -o build/lib.linux-x86_64-2.7/_mysql.so
    /usr/bin/ld: cannot find -lmysqlclient
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    Complete output from command /mnt/data/mysql_streamer/mysql_streamer-master/venv/docs/bin/python2.7 -c "import setuptools, tokenize;__file__='/mnt/data/mysql_streamer/mysql_streamer-master/venv/docs/build/MySQL-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zrNOEa-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/data/mysql_streamer/mysql_streamer-master/venv/docs/include/site/python2.7:
    running install

running build

running build_py

running build_ext

building '_mysql' extension

gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Dversion_info=(1,2,3,'final',0) -D__version__=1.2.3 -I/usr/include/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o -fPIC -g -fabi-version=2 -fno-omit-frame-pointer -fno-strict-aliasing

gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/_mysql.o -L/usr/lib -L/usr/lib64 -lmysqlclient -lpthread -lm -lrt -ldl -lpython2.7 -o build/lib.linux-x86_64-2.7/_mysql.so

/usr/bin/ld: cannot find -lmysqlclient

collect2: error: ld returned 1 exit status

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /mnt/data/mysql_streamer/mysql_streamer-master/venv/docs/bin/python2.7 -c "import setuptools, tokenize;__file__='/mnt/data/mysql_streamer/mysql_streamer-master/venv/docs/build/MySQL-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zrNOEa-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/data/mysql_streamer/mysql_streamer-master/venv/docs/include/site/python2.7 failed with error code 1 in /mnt/data/mysql_streamer/mysql_streamer-master/venv/docs/build/MySQL-python
Storing debug log for failure in /root/.pip/pip.log

Something went wrong! Sending 'venv/docs' back in time, so make knows it's invalid.
ERROR: InvocationError: '/mnt/data/mysql_streamer/mysql_streamer-master/bin/venv-update venv= /mnt/data/mysql_streamer/mysql_streamer-master/venv/docs install= -r /mnt/data/mysql_streamer/mysql_streamer-master/requirements.d/docs.txt -r /mnt/data/mysql_streamer/mysql_streamer-master/requirements-opensource.txt'
pre-commit installed: PyYAML==3.12,aspy.yaml==0.2.2,cached-property==1.3.0,functools32==3.2.3.post2,jsonschema==2.6.0,nodeenv==1.1.2,pre-commit==0.13.3,venv-update==1.0.1,virtualenv==15.1.0,wheel==0.29.0,wsgiref==0.1.2
pre-commit runtests: PYTHONHASHSEED='2193082984'
pre-commit runtests: commands[0] | /mnt/data/mysql_streamer/mysql_streamer-master/bin/venv-update venv= /mnt/data/mysql_streamer/mysql_streamer-master/venv/pre-commit install= -r /mnt/data/mysql_streamer/mysql_streamer-master/requirements.d/pre_commit.txt
> virtualenv venv/pre-commit
Keeping valid virtualenv from previous run.
> pip install --find-links=file:///root/.cache/pip-faster/wheelhouse venv-update==1.0.1
Requirement already satisfied (use --upgrade to upgrade): venv-update==1.0.1 in ./venv/pre-commit/lib/python2.7/site-packages
Cleaning up...
> pip-faster install --upgrade --prune -r requirements.d/pre_commit.txt
Requirement already up-to-date: pre-commit>=0.4.2 in ./venv/pre-commit/lib/python2.7/site-packages (from -r /mnt/data/mysql_streamer/mysql_streamer-master/requirements.d/pre_commit.txt (line 1))
Cleaning up...
pre-commit runtests: commands[1] | pre-commit
Traceback (most recent call last):
  File "/mnt/data/mysql_streamer/mysql_streamer-master/venv/pre-commit/bin/pre-commit", line 7, in <module>
    from pre_commit.main import main
  File "/mnt/data/mysql_streamer/mysql_streamer-master/venv/pre-commit/lib/python2.7/site-packages/pre_commit/main.py", line 7, in <module>
    import pre_commit.constants as C
  File "/mnt/data/mysql_streamer/mysql_streamer-master/venv/pre-commit/lib/python2.7/site-packages/pre_commit/constants.py", line 3, in <module>
    import pkg_resources
  File "/mnt/data/mysql_streamer/mysql_streamer-master/venv/pre-commit/lib/python2.7/site-packages/pkg_resources/__init__.py", line 48, in <module>
    import six
ImportError: No module named six
ERROR: InvocationError: '/mnt/data/mysql_streamer/mysql_streamer-master/venv/pre-commit/bin/pre-commit'
__________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________
ERROR:   py27: commands failed
ERROR:   docs: commands failed
ERROR:   pre-commit: commands failed
make: *** [test] Error 1

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!
