### ISSUE TITLE
Cannot fetch index base URL https://pypi.yelpcorp.com/simple/

### ISSUE THREAD

**Issue by mazjs** [Yelp/mysql_streamer#20]
Obtaining file:///code (from -r /code/requirements-opensource.txt (line 5))
  Running setup.py (path:/code/setup.py) egg_info for package from file:///code

Downloading/unpacking MySQL-python==1.2.5 (from -r /code/requirements-opensource.txt (line 8))
  Cannot fetch index base URL https://pypi.yelpcorp.com/simple/
  Running setup.py (path:/code/virtualenv_run/build/MySQL-python/setup.py) egg_info for package MySQL-python

Downloading/unpacking PyMySQL==0.6.7 (from -r /code/requirements-opensource.txt (line 9))
  Cannot fetch index base URL https://pypi.yelpcorp.com/simple/
Downloading/unpacking PyStaticConfiguration==0.10.2 (from -r /code/requirements-opensource.txt (line 10))
  Cannot fetch index base URL https://pypi.yelpcorp.com/simple/
  Downloading PyStaticConfiguration-0.10.2.tar.gz
  Running setup.py (path:/code/virtualenv_run/build/PyStaticConfiguration/setup.py) egg_info for package PyStaticConfiguration

Downloading/unpacking PyYAML==3.11 (from -r /code/requirements-opensource.txt (line 11))
  Cannot fetch index base URL https://pypi.yelpcorp.com/simple/
  Running setup.py (path:/code/virtualenv_run/build/PyYAML/setup.py) egg_info for package PyYAML

Downloading/unpacking SQLAlchemy==1.0.12 (from -r /code/requirements-opensource.txt (line 12))
  Cannot fetch index base URL https://pypi.yelpcorp.com/simple/
  Running setup.py (path:/code/virtualenv_run/build/SQLAlchemy/setup.py) egg_info for package SQLAlchemy

**https://pypi.yelpcorp.com/simple/** is down ?

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!
