### ISSUE TITLE
Error:Test Makefile

### ISSUE THREAD

**Issue by sssadhu** [Yelp/mysql_streamer#21]
Hi,

Encountering 
<img width="633" alt="screen shot 2017-08-09 at 12 14 50 am" src="https://user-images.githubusercontent.com/11742985/29109731-f66e8418-7c98-11e7-8018-50eed01e26b3.png">
error while running 'make -f Makefile-opensource test' command. Can you help us resolve the issue.
/bin/sh: 1: tox: not found make: *** [test] Error 127

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!
