### ISSUE TITLE
Are you guys maintaining this repository?

### ISSUE THREAD

**Issue by ravindranathakila** [Yelp/mysql_streamer#22]
Could you point me to a stable release/commit? Thanks in advance!

**Comment by telemmaite** [comment]
What happened is this project dead?

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!

We published this repo to serve as an example for our tech blog series, but didn't maintain it externally. If you're interested in CDC streaming, check out [Debezium](https://debezium.io/)!
