### ISSUE TITLE
make: *** [test] Error 127

### ISSUE THREAD

**Issue by qinzl1** [Yelp/mysql_streamer#23]
centos run “make -f Makefile-opensource test”   throws error：
OPEN_SOURCE_MODE=True FORCE_AVOID_INTERNAL_PACKAGES=True tox -c tox-opensource.ini
/bin/sh: tox: command not found
make: *** [test] Error 127

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!
