### ISSUE TITLE
Error while creating Docker image from Dockerfile

### ISSUE THREAD

**Issue by chinmayprabhu** [Yelp/mysql_streamer#24]
Hi,

I am trying to create docker image from Dockerfile present in mysql_streamer But it is giving me following errors : 

`Obtaining file:///code (from -r /code/requirements.txt (line 5))
Collecting MySQL-python==1.2.5 (from -r /code/requirements.txt (line 8))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003747360>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mysql-python/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003747398>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mysql-python/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000037473d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mysql-python/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003747408>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mysql-python/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003747440>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mysql-python/
  Downloading MySQL-python-1.2.5.zip (108kB)
Collecting PyMySQL==0.6.7 (from -r /code/requirements.txt (line 9))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000366f5c8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pymysql/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000366f600>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pymysql/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000366f638>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pymysql/
`

Any idea what this error might be? 

Thanks and Regards,

Chinmay Prabhu

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!
