### ISSUE TITLE
error installing data_pipeline and mrjob

### ISSUE THREAD

**Issue by ronnie8778** [Yelp/mysql_streamer#26]
When I install data_pipeline, it gave me the following issue:
kafka-utils 1.7.1 has requirement kafka-python<1.5.0,>=1.3.2, but you'll have kafka-python 0.9.5 which is incompatible.
Cannot uninstall 'pyOpenSSL'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

and when installing mrjob I got the following:
kafka-utils 1.7.1 has requirement kafka-python<1.5.0,>=1.3.2, but you'll have kafka-python 0.9.5 which is incompatible.

Anyway to update kafka-utils?

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!
