### ISSUE TITLE
No distributions at all found for geogrid

### ISSUE THREAD

**Issue by Geesu** [Yelp/mysql_streamer#6]
Is `geogrid` an internal package? Was trying to run the integration tests (`make -f Makefile-opensource itest`) and I'm getting this error:

```
No distributions at all found for geogrid==1.0.8 (from -r /code/requirements-opensource.txt (line 20))
```

**Comment by premsantosh** [comment]
Hey @Geesu, yes geogrid is an internal package. We are in the process of setting up the travis builds for this project (which might require some code changes). Kindly check back in a few days.

**Comment by DeanWei** [comment]
@premsantosh ,Any update regarding this issue? Thanks

**Comment by Geesu** [comment]
@premsantosh any update on adding the internal package? I noticed there hasn't really been much activity on the project. Just hoping there is internally and it hasn't been published yet.

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!
